### ISSUE TITLE
Profile Management

### ISSUE THREAD

**Issue by JoshEddie** [tdtrevathan/group12#18]
- Client Profile Management (After client registers they should login first to complete the profile). Following fields will be on Profile page / form:
	- Full Name (50 characters, required)
	- Address 1 (100 characters, required)
	- Address 2 (100 characters, optional)
	- City (100 characters, required)
	- State (Drop Down, selection required) DB will store 2 character state code
	- Zipcode (9 characters, at least 5 character code required)

**Comment by tdtrevathan** [comment]
validation added
